local module = {}

module.table =
{
    "EXTRASUNNY LA",
    "SUNNY LA",
    "EXTRASUNNY SMOG LA",
    "SUNNY SMOG LA",
    "CLOUDY LA",
    "SUNNY SF",
    "EXTRASUNNY SF",
    "CLOUDY SF",
    "RAINY SF",
    "FOGGY SF",
    "SUNNY VEGAS",
    "EXTRASUNNY VEGAS",
    "CLOUDY VEGAS",
    "EXTRASUNNY COUNTRYSIDE",
    "SUNNY COUNTRYSIDE",
    "CLOUDY COUNTRYSIDE",
    "RAINY COUNTRYSIDE",
    "EXTRASUNNY DESERT",
    "SUNNY DESERT",
    "SANDSTORM DESERT",
    "UNDERWATER",
    "EXTRACOLOURS 1",
    "EXTRACOLOURS 2",
}

return module